[build-system]
requires = ["flit_core >=3.2,<4", "setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "CSuite"
authors = [{name = "Fivos", email = "fivosd@hotmail.com"}]
dynamic = ["version", "description"]